### PR TITLE
DDPB-3590: Remove court order creation code from lay registration

### PR DESCRIPTION
**Pull request by coderste**
In this PR we have removed the code which creates a court order for new
registrations. We have done this because the court order schema will
change soon and the first part to changing the schema is making sure no
new court orders are created when a users registers

Fixes DDPB-3590

## Checklist
- [x] I have performed a self-review of my own code
- [ ] I have updated documentation (Confluence/ADR/tech debt doc) where relevant **N/A**
- [ ] I have added tests to prove my work **N/A**
- [ ] The product team have approved these changes

### CODE REVIEW

**Review by acsauk-mojd — DISMISSED** [review]
Nice job - I know this was a pain to test but hopefully the registration flow makes more sense now 🙌 

:shipit:

**Comment by coderste** [comment]
> Nice job - I know this was a pain to test but hopefully the registration flow makes more sense now 🙌
> 
> :shipit:

It definitely does 😄

**Review by acsauk-mojd — APPROVED** [review]
:shipit:

**Review by acsauk-mojd — APPROVED** [review]
Ahhh yeah that test is right near the end of the suite. Third time lucky :shipit:

**Pull request merged**
